INSERT INTO public.responses
  (graduation_semester, field_of_study, internship_experience, job_status, role_types, biggest_concern)
VALUES
  ('Spring 2026', 'Accounting', 'one', 'exploring', ARRAY['full_time'], 'Getting enough interviews'),
  ('Fall 2026', 'Computer Engineering', 'multiple', 'yes', ARRAY['full_time'], 'Choosing between two offers'),
  ('Spring 2027', 'Biology', 'none', 'exploring', ARRAY['grad_school'], 'Application deadlines'),
  ('Fall 2025', 'Data Science', 'multiple', 'yes', ARRAY['full_time', 'entrepreneurship'], 'Burnout'),
  ('Other', 'English', 'none', 'no', ARRAY['freelance'], 'Finding stable income'),
  ('Spring 2026', 'Mechanical Engineering', 'one', 'yes', ARRAY['full_time'], 'Relocation costs'),
  ('Fall 2026', 'Political Science', 'none', 'exploring', ARRAY['grad_school', 'unsure'], 'Whether to work before grad school'),
  ('Spring 2027', 'Nursing', 'multiple', 'yes', ARRAY['full_time'], 'Passing licensure exams'),
  ('Fall 2025', 'Management Information Systems', 'one', 'yes', ARRAY['full_time'], 'Negotiating salary'),
  ('Spring 2026', 'Graphic Design', 'none', 'exploring', ARRAY['freelance', 'full_time'], 'Building a stronger portfolio'),
  ('Fall 2026', 'Chemistry', 'one', 'no', ARRAY['grad_school'], 'Research funding'),
  ('Spring 2027', 'Civil Engineering', 'multiple', 'yes', ARRAY['full_time'], 'Professional certification'),
  ('Fall 2025', 'Mathematics', 'none', 'exploring', ARRAY['full_time', 'grad_school'], 'Deciding between industry and academia'),
  ('Spring 2026', 'Sociology', 'one', 'exploring', ARRAY['grad_school'], 'Job market uncertainty'),
  ('Fall 2026', 'Supply Chain Management', 'multiple', 'yes', ARRAY['full_time'], 'Moving to a higher cost-of-living city'),
  ('Spring 2027', 'Communications', 'one', 'no', ARRAY['full_time', 'freelance'], 'Standing out to employers'),
  ('Other', 'History', 'none', 'exploring', ARRAY['grad_school', 'unsure'], 'Not knowing the right next step'),
  ('Fall 2025', 'Finance', 'multiple', 'yes', ARRAY['full_time'], 'Work-life balance'),
  ('Spring 2026', 'Public Health', 'one', 'exploring', ARRAY['grad_school', 'full_time'], 'Competing priorities'),
  ('Fall 2026', 'Cybersecurity', 'multiple', 'yes', ARRAY['full_time'], 'Keeping skills current'),
  ('Spring 2027', 'Education', 'none', 'exploring', ARRAY['full_time'], 'Finding the right school district'),
  ('Fall 2025', 'Marketing', 'one', 'yes', ARRAY['full_time', 'freelance'], 'Career growth'),
  ('Spring 2026', 'Physics', 'multiple', 'exploring', ARRAY['grad_school'], 'Choosing a specialization'),
  ('Fall 2026', 'Business Analytics', 'one', 'yes', ARRAY['full_time'], 'Imposter syndrome'),
  ('Spring 2027', 'Anthropology', 'none', 'no', ARRAY['unsure'], 'Limited entry-level roles'),
  ('Other', 'Art', 'one', 'exploring', ARRAY['freelance', 'entrepreneurship'], 'Finding clients consistently'),
  ('Fall 2025', 'Computer Science', 'multiple', 'yes', ARRAY['full_time'], 'Team fit'),
  ('Spring 2026', 'Economics', 'none', 'exploring', ARRAY['full_time', 'grad_school'], 'Whether more school is worth it'),
  ('Fall 2026', 'Healthcare Administration', 'one', 'yes', ARRAY['full_time'], 'Leadership readiness'),
  ('Spring 2027', 'Information Systems', 'multiple', 'yes', ARRAY['full_time', 'entrepreneurship'], 'Long-term career direction');
